// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Odevdeneme
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Position")]
            public string Position { get; set; }

            [ColumnName(@"Age")]
            public string Age { get; set; }

            [ColumnName(@"Markey Value In Millions(£)")]
            public float Markey_Value_In_Millions___ { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Club")]
            public string Club { get; set; }

            [ColumnName(@"Matches")]
            public float Matches { get; set; }

            [ColumnName(@"Goals")]
            public string Goals { get; set; }

            [ColumnName(@"Own Goals")]
            public float Own_Goals { get; set; }

            [ColumnName(@"Assists")]
            public string Assists { get; set; }

            [ColumnName(@"Yellow Cards")]
            public string Yellow_Cards { get; set; }

            [ColumnName(@"Second Yellow Cards")]
            public float Second_Yellow_Cards { get; set; }

            [ColumnName(@"Red Cards")]
            public string Red_Cards { get; set; }

            [ColumnName(@"Number Of Substitute In")]
            public float Number_Of_Substitute_In { get; set; }

            [ColumnName(@"Number Of Substitute Out")]
            public float Number_Of_Substitute_Out { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
